

stat_meanings = {'str': 'Strength',
                 'int': 'Intellect',
                 'openwounds': 'Open Wounds',
                 'crush': 'Crushing Blow',
                 'dmg%': 'Enhanced Damage',
                 'stupidity': 'Blind Enemy',
                 'dmg-min': 'Minimum Damage',
                 'att%': 'Attack Rating',
                 'mana-kill': 'Mana After Kill',
                 'dmg-undead': 'Damage to Undead',
                 'att-undead': 'Attack Rating Against Undead',
                 'swing2': 'Increased Attack Speed',
                 'ac': 'Defense',
                 'fire-min': 'Fire Damage Minimum',
                 'fire-max': 'Fire Damage Maximum',
                 'regen-mana': 'Regenerate Mana',
                 'ltng-min': 'Minimum Lighting Damage',
                 'ltng-max': 'Maximum Lightning Damage',
                 'att': 'Attack Rating',
                 'pois-min': 'Poison Damage Minimum',
                 'pois-max': 'Poison Damage Maximum',
                 'pois-len': 'Poison Damage Duration',
                 'res-pois': 'Poison Resistance',
                 'freeze': 'Freeze Target ',
                 'res-cold': 'Cold Resistance',
                 'light': 'Light Radius',
                 'swing3': 'Increased Attack Speed',
                 'dmg-max': 'Maximum Damage',
                 'res-all': 'All Resistances',
                 'dmg-ltng': 'Lightning Damage',
                 'mana': 'Mana',
                 'manasteal': 'Mana Stolen Per Hit',
                 'dmg-fire': 'Fire Damage',
                 'ease': 'Requirements',
                 'nec': 'Necromancer Skill',
                 'lifesteal': 'Life Stolen Per Hit',
                 'enr': 'Energy',
                 'res-ltng': 'Lightning Resistance',
                 'cast2': 'Faster Cast Rate',
                 'skill': 'Class Skill ',
                 'dex': 'Dexterity',
                 'cold-min': 'Minimum Cold Damage',
                 'cold-max': 'Maximum Cold Damage',
                 'cold-len': 'Cold Damage Duration',
                 'howl': 'Flee',
                 'res-fire': 'Fire Resistance',
                 'knock': 'Knockback',
                 'pal': 'Paladin',
                 'dmg-norm': 'Additional Damage',
                 'red-mag': 'Magic Damage Reduced',
                 'dmg-cold': 'Additional Cold Damage',
                 'regen': 'Regenerate Life',
                 'thorns': 'Thorns',
                 'vit': 'Vitality',
                 'swing1': 'Increased Attack Speed',
                 'slow': 'Slows Target',
                 '*enr': 'Energy Cost',
                 'regen-stam': 'Regenerate Stamina',
                 'hp': 'Life',
                 'ignore-ac': 'Ignore Defense',
                 'deadly': 'Deadly Strike',
                 'mag%': 'Enhanced Magic Find',
                 'dur': 'Duration',
                 'dmg-mag': 'Additional Magic Damage',
                 'fireskill': 'Fire Skills',
                 'allskills': 'All Skills',
                 'res-pois-len': 'Poison Length Reduced',
                 'balance2': 'Faster Hit Recovery',
                 'dmg-pois': 'Additional Poison Damage',
                 'noheal': 'Prevent Monster Heal',
                 '*hp': 'Life Cost',
                 'red-dmg': 'Damage Reduced',
                 'gold%': 'Extra Gold',
                 'nofreeze': 'Cannot Be Frozen',
                 'res-pois-max': 'Max Poison Resistance',
                 'cast3': 'Faster Cast Rate',
                 'reduce-ac': 'Reduced Target Defense',
                 'res-fire-max': 'Max Fire Resistance',
                 'dmg-ac': 'Reduced Defense Per Hit',
                 'sor': 'Sorceress Skills',
                 'magicarrow': 'Magic Arrows',
                 'explosivearrow': 'Explosive Arrows',
                 'pierce': 'Piercing Attack',
                 'pierce-cold': 'Enemy Cold Resistance',
                 'ama': 'Amazon Skills',
                 'light-thorns': 'Lightning Thorns',
                 'ac-miss': 'Defense Vs Missiles',
                 'ac%': 'Enhanced Defense',
                 'dmg-to-mana': 'Recieved Damage To Mana',
                 'half-freeze': 'Half Freeze Duration',
                 'move2': 'Movement',
                 'stam': 'Stamina',
                 'stamdrain': 'Stamina Drain',
                 'block': 'Block',
                 'res-all-max': 'Maximum All Resistances',
                 'ac-hth': 'Defense Vs Melee',
                 'res-cold-max': 'Maximum Cold Resistance',
                 'red-dmg%': 'Damage Reduced Percentage',
                 'block2': 'Faster Block Rate',
                 'bloody': 'Bloody?',
                 'mana%': 'Enhanced Mana',
                 'hit-skill': 'Cast Skill On Strike',
                 'gethit-skill': 'Cast Skill On Struck',
                 'indestruct': 'Indestructable',
                 'dru': 'Druid Skills',
                 'vit/lvl': 'Vitality Per Level',
                 'rep-dur': 'Repair Durability',
                 'cast1': 'Faster Cast Rate',
                 'charged': 'Charged',
                 'att-und/lvl': 'Attack Rating Per Level',
                 'dmg-und/lvl': 'Damage To Undead Per Level',
                 'hp/lvl': 'Life Per Level',
                 'mana/lvl': 'Mana Per Level',
                 'skilltab': 'Class Skills',
                 'dmg-demon': 'Damage To Demons',
                 'att-demon': 'Attack Rating For Demons',
                 'demon-heal': 'Life After Demon Kill',
                 'sock': 'Sockets',
                 'gold%/lvl': 'Enhanced Gold Per Level',
                 'mag%/lvl': 'Enhanced Magic Damage Per Level',
                 'deadly/lvl': 'Deadly Strike Per Level',
                 'dmg/lvl': 'Damage Per Level',
                 'res-ltng-max': 'Maximum Lightning Resistance',
                 'abs-fire': 'Absorb Fire',
                 'att-skill': 'Cast on Attack',
                 'ac/lvl': 'Defense Per Level',
                 'res-ltng/lvl': 'Lighting Resistance Per Level',
                 'dmg-dem/lvl': 'Damage To Demon Per Level',
                 'bar': 'Barbarian Skills',
                 'hp%': 'Enhanced Life',
                 '*hit-skill': '*hit-skill?',
                 '*gethit-skill': '*gethit-skill?',
                 'att/lvl': 'Attack Rating Per Level',
                 'abs-ltng': 'Absorb Lightning',
                 '*charged': '*charged?',
                 '*vit': '*vit?',
                 'att-dem/lvl': 'Attack Rating For Demons Per Level',
                 'thorns/lvl': 'Thorns Per Level',
                 'abs-cold': 'Absorb Cold',
                 '*mana': '*mana?',
                 'dex/lvl': 'Dexterity Per Level',
                 'abs-cold/lvl': 'Absorb Cold Per Level',
                 'str/lvl': 'Strength Per Level',
                 'dmg%/lvl': 'Enhanced Damage Per Level',
                 'abs-ltng%': 'Enhanced Absorb Lightning Per Level',
                 'abs-fire/lvl': 'Enhanced Absorb Fire Per Level',
                 'abs-fire%': 'Enhanced Absorb Fire',
                 'abs-cold%': 'Enhanced Absord Cold',
                 'rep-quant': 'Replenish Quantity',
                 'stack': 'Stack Size',
                 'ass': 'Assassin Skills',
                 'heal-kill': 'Life On Kill',
                 'reanimate': 'Reanimate',
                 'pierce-pois': 'Enemy Poison Resistance',
                 'rip': 'Rest In Peace',
                 'aura': 'Aura',
                 'all-stats': 'All Stats',
                 'dmg': 'Damage',
                 'kill-skill': 'Cast Skill On Kill',
                 'pierce-fire': 'Enemy Fire Resistance',
                 'pierce-ltng': 'Enemy Lightning Resistance',
                 'ethereal': 'Ethereal',
                 'dmg-elem': 'Damage For All Elements',
                 'oskill': 'oskill?',
                 'extra-ltng': 'Extra Lightning Damage',
                 'extra-cold': 'Extra Cold Damage',
                 'extra-fire': 'Extra Fire Damage',
                 'death-skill': 'Cast Skill On Death',
                 'skill-rand': 'Random Skill',
                 'cheap': 'Gold Discount',
                 'stam/lvl': 'Stamina Per Level',
                 'addxp': 'Additional Experience',
                 'extra-pois': 'Extra Poison Damage',
                 'levelup-skill': 'Cast Skill On Levelup',
                 'randclassskill': 'Random Class Skill',
                 }
